### PR TITLE
feat: add k8s cluster upgrade playbook

### PR DESCRIPTION
**Pull request by okozachenko1203**

### CODE REVIEW

**Comment by mnaser** [comment]
This still needs a bit more work, which is primarily:

- Implement #90 for smoother restarts
- Properly detecting that things don't restart
- run multiple upgrades in serial if we are jumping multiple versions (aka 1.22 to 1.28 means we upgrade 1.23... 1.24.. etc)

**Comment by okozachenko1203** [comment]
kube-api was unhealthy during upgrade because the etcd master was restarted one time 
```sh
level=warning msg="Network status error received, restarting client connections" error="an error on the server (\"[+]ping ok
[+]log ok
[-]etcd failed: reason withheld
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/priority-and-fairness-config-consumer ok
[+]poststarthook/priority-and-fairness-filter ok
[+]poststarthook/storage-object-count-tracker-hook ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok
[+]poststarthook/priority-and-fairness-config-producer ok
[+]poststarthook/start-cluster-authentication-info-controller ok
[+]poststarthook/start-kube-apiserver-identity-lease-controller ok
[+]poststarthook/start-kube-apiserver-identity-lease-garbage-collector ok
[+]poststarthook/start-legacy-token-tracking-controller ok
[+]poststarthook/aggregator-reload-proxy-client-cert ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
[+]poststarthook/apiservice-openapi-controller ok
[+]poststarthook/apiservice-openapiv3-controller ok
healthz check failed\") has prevented the request from succeeding (get healthz.meta.k8s.io)" subsys=k8s-client

```

**Comment by okozachenko1203** [comment]
the first etcd is always facing this error and restart one time required
```sh
{"level":"info","ts":"2023-12-11T16:11:24.951749Z","caller":"embed/etcd.go:378","msg":"closed etcd server","name":"k8s-cluster-upgrade-1","data-dir":"/var/lib/etcd","advertise-peer-urls":["https://172.17.0.3:2380"],"advertise-client-urls":["https://172.17.0.3:2379"]}
{"level":"fatal","ts":"2023-12-11T16:11:24.95178Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 172.17.0.3:2380: bind: address already in use","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\tgo.etcd.io/etcd/server/v3/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\tgo.etcd.io/etcd/server/v3/etcdmain/main.go:40\nmain.main\n\tgo.etcd.io/etcd/server/v3/main.go:31\nruntime.main\n\truntime/proc.go:250"}
```

**Comment by okozachenko1203** [comment]
@mnaser i feel like we need to choose other application for validation because this cilium operator is too sensitive to cluster healthy and it doesn't allow even blip

**Comment by okozachenko1203** [comment]
> @mnaser i feel like we need to choose other application for validation because this cilium operator is too sensitive to cluster healthy and it doesn't allow even blip

nvm, after set throttle 1 for kubelet restart task, the verification step works as expected.

**Pull request merged**
