### PR TITLE
feat(role:cilium): Upgrade cilium version

### PR DESCRIPTION
**Pull request by okozachenko1203**
1.10.20 -> 1.13.3

fix https://github.com/vexxhost/atmosphere/issues/423

### CODE REVIEW

**Comment by mnaser** [comment]
It looks like the idempotence tests are failing, which means that somehow Cilium is changing states...

Maybe there is some random variable that we have to set somewhere?

**Comment by okozachenko1203** [comment]
> It looks like the idempotence tests are failing, which means that somehow Cilium is changing states...
> 
> Maybe there is some random variable that we have to set somewhere?

yeah, if we don't specify the certificates for cilium and hubble, it generates them using `genCA` tpl func randomly.
```
default, cilium-ca, Secret (v1) has changed:
  # Source: cilium/templates/cilium-ca-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: cilium-ca
    namespace: default
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   ca.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   ca.key: '++++++++ # (1675 bytes)'

default, hubble-ca-secret, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/ca-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-ca-secret
    namespace: default
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   ca.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   ca.key: '++++++++ # (1675 bytes)'

default, hubble-server-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/server-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-server-certs
    namespace: default
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   tls.crt: '-------- # (1216 bytes)'
-   tls.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   tls.crt: '++++++++ # (1220 bytes)'
+   tls.key: '++++++++ # (1679 bytes)'
  type: kubernetes.io/tls
```

**Comment by okozachenko1203** [comment]
`cilium-ca` and `hubble-ca-secret` can be static once we provide `tls.ca.cert` and `tls.ca.key` values.
But `hubble-server-certs` will be dynamic every helm upgrade because it is generated by `genSignedCert` tpl func.
https://github.com/vexxhost/ansible-collection-kubernetes/blob/e783aad4190a797c3037849f176e07b179aace23/charts/cilium/templates/hubble/tls-helm/server-secret.yaml#L6

**Comment by mnaser** [comment]
I think the issue with this is that every single time that a new deployment is issued, those certificates will be changed and then potentially some things can stop working...

We don't use Hubble and any features that depend on the CA so I think the right combination would disable the cilium-ca:

https://github.com/cilium/cilium/blob/v1.13.4/install/kubernetes/cilium/templates/cilium-ca-secret.yaml

For Hubble, we don't use it so we can probably find the values to disable it and the generation of the secret that's being used.

**Comment by mnaser** [comment]
@okozachenko1203 indeed Hubble seems to be enabled by default now.

**Comment by okozachenko1203** [comment]
@mnaser yeah, hubble disabled and all cert gen stuff eliminated.

**Comment by okozachenko1203** [comment]
@mnaser i think we need to bypass/skip this role var naming rule

**Comment by mnaser** [comment]
> @mnaser i think we need to bypass/skip this role var naming rule

We can ignore it for now. We can get back to it later.

**Pull request merged**
